### ISSUE TITLE
Valkyrie: Importer and Exporter index page error

### ISSUE THREAD

**Issue by KatharineV** [notch8/adventist_knapsack#758]
When I try to sort importers on ADL Staging, the Last Run and Next Run sort features don't work. They generate the following error message. We need these sort features to work because we use them frequently while managing our importers, and they worked prior to the latest upgrade. 

![Image](https://github.com/user-attachments/assets/4a5333a4-efcf-49aa-91db-52b7aa091842)

## Acceptance Criteria

- [ ] A user should be able to sort and paginate through the importer and exporter tables

**Comment by ShanaLMoore** [comment]
the server logs produces this error: 



![Image](https://github.com/user-attachments/assets/6f49c21f-2797-45e3-82b8-6cd4a8a8bfa0)

**Comment by ShanaLMoore** [comment]
Slack Thread: https://assaydepot.slack.com/archives/C0313NK5NMA/p1726166493597369

**Comment by ShanaLMoore** [comment]
# QA RESULTS:

**Comment by KatharineV** [comment]
Confirmed: it as expected for importers and exporters when I try to sort and page through on multiple staging tenants.

**Comment by KatharineV** [comment]
Folks, the importer "last run" sort feature was fixed on staging, but post cutover, it's not working correctly on prod. I can tell it isn't working correctly because we have at least 27 importers that I recorded myself as running between April 2024 and the present, and the sort that should show most recent importers at the top is only showing one from 2024.

[Importer ](https://adl.b2.adventistdigitallibrary.org/importers?locale=en)page prior to any sort:
![Image](https://github.com/user-attachments/assets/86ed1899-2bd6-4e27-9c74-aaf2015f8caf)


Clicked Last Run once:
![Image](https://github.com/user-attachments/assets/cc4ca637-75b8-4654-8f81-c541052ba83e)


Clicked Last Run a second time: 
![Image](https://github.com/user-attachments/assets/e862224d-dcbc-41ff-abf5-30e3f7787a5a)

**Comment by ShanaLMoore** [comment]
In prod we needed to run a command to fix this. I just ran it, could you try again and let me know if you still see the problem @KatharineV 

for future self: `rake bulkrax:update_status_messages`

**Comment by ShanaLMoore** [comment]
cc @KatharineV actually I still see the issue. I'll need to have a closer look

**Comment by ShanaLMoore** [comment]
`bundle exec rake bulkrax:resave_importers` was the command that needed to be run

**Comment by ShanaLMoore** [comment]
@KatharineV Please try again: [demo](https://share.zight.com/BluPlDdA)

**Comment by KatharineV** [comment]
@ShanaLMoore yes, I can confirm I see the Last Run sort working on prod now. Thanks!

**Comment by KatharineV** [comment]
The Ajax error is back on staging and it periodically messes up my ability to work through the dashboard.
